### ISSUE TITLE
[Bug] No longer able to add slots in dialog

### ISSUE THREAD

**Issue by davidkreynolds** [wxGlade/wxGlade#411]
From the latest commit:
When building a dialog, the dialog form appears with one slot, labelled Slot rather than Slot 0.
It is possible to add a control in that slot, but Ctrl-A doesn't work when adding more slots.

**Comment by DietmarSchwertberger** [comment]
Well, actually, you can add a sizer or a single control to this. Similar as with e.g. a frame.
This is almost the same as with revision 0.9.x but there the SLOT was not shown and so it was clear that a sizer had to be added. ("Almost" because in 0.9 it had to be a sizer, not something else.)

I need to check how to make this clearer, e.g. with a checkbox "Add sizer".

**Comment by davidkreynolds** [comment]
Ah yes. I've added a sizer, and very easy to add a number of slots to that. As you have said, maybe a checkbox "Add sizer" when the dialog is crreated would be good, but this is fine now I know.

**Comment by DietmarSchwertberger** [comment]
OK, I have updated the dialog with "Add sizer". Also, the tooltip help is better now and the information is also displayed on the Properties tab.

Thanks a lot for using and testing the master branch.

**Comment by davidkreynolds** [comment]
Dietmar,

 

Thanks for changing this. I’ll continue to regularly clone the the master branch,

 

Thanks for all your work on this,

 

David.
