### ISSUE TITLE
Bind events to objects instead of frame.

### ISSUE THREAD

**Issue by TonyReinberger** [wxGlade/wxGlade#507]
This is related to issue #353. I'm generating Python3 code and using the latest REV_1.0 branch.

I came across this a little over a year ago but then dropped my project. I found that the bug still exists so here is the problem I had and my solution. 

I added wx.EVT_LEFT_DOWN to wxChoice and named the handler but it doesn't get called. It appears that the code generator creates the following code.

    `self.Bind(wx.EVT_LEFT_DOWN, self._handle_find_serial_ports, self.choice_serial_port)`

This binds it to the frame instead of the object receiving the click. I changed it to the following and it works as expected.

    `self.choice_serial_port.Bind(wx.EVT_LEFT_DOWN, self._handle_find_serial_ports)`

I looked in codegen/py_codegen.py and change line 388 from

    `tmpl = '%(tab)sself.Bind(%(event)s, %(handler)s, %(obj_name_id)s)\n'`

to

    `tmpl = '%(tab)s%(obj_name_id)s.Bind(%(event)s, %(handler)s)\n'`

I'm not sure if this could cause problems with other event types but based on what I saw in #353 and wxPython API, the change seems to create the proper use of bind.

Cheers,

Tony

**Comment by Swimfin** [comment]
I came across [this](https://wiki.wxpython.org/self.Bind%20vs.%20self.button.Bind) in the wxPyWiki which actually describes the problem I had. I'm not sure what the correct option / solution for wxGlade would be but it would be nice to find a way so that new users would not have to spend a lot of time repeating the search to find out why some events may not work. Maybe a checkbox to set the binding method and a tool tip in wxGlade.

**Comment by DietmarSchwertberger** [comment]
Well, the event binding code pre-dates my work on wxGlade. Personally I would probably have implemented it differently, but I don't want to change it now as it might introduce compatibility issues.

I still do not have a good idea how to implement #353. The problem is that there's no way to programatically read all the required infos about the available events and I dislike the idea of hardcoding all event types.

**Comment by DietmarSchwertberger** [comment]
I'm willing to implement the change. I have asked on the mailing list whether anyone has objections.

**Comment by DietmarSchwertberger** [comment]
The change is implemented for Python. Please try the master branch.
