### ISSUE TITLE
Save problem Ubuntu 

### ISSUE THREAD

**Issue by wyzarddoc** [wxGlade/wxGlade#538]
Got the following error when trying to save new project. Note I cannot start wxGlade any way but to bring the file into Thonny and then run the file from the editor

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   'NoneType' object has no attribute 'SendSizeEventToParent'

Application stack traceback:
  File "/home/doc/Downloads/pythonworking/wxGlade-1.0.5/new_properties.py", line 3351, in on_button
    self.callback()
  File "/home/doc/Downloads/pythonworking/wxGlade-1.0.5/edit_windows.py", line 768, in on_preview
    compat.wxWindow_SendSizeEventToParent(self.preview_widget)
  File "/home/doc/Downloads/pythonworking/wxGlade-1.0.5/compat.py", line 217, in wxWindow_SendSizeEventToParent3
    item.SendSizeEventToParent(flags)

Date and time:       2024-01-16T13:52:44.673346
Python version:      3.10.12
wxPython version:    4.2.1
wxWidgets platform:  __WXGTK__
wxGlade version:     1.0.5

**Comment by DietmarSchwertberger** [comment]
This is fixed in 1.1.0 alpha already.

Could you please go to `edit_windows.py` and indent the `if wx.Platform == '__WXGTK__': ` part by one level?

```
class PreviewMixin(object):
    ...
    def on_preview(self, refresh=False):
        ...
        if self.preview_widget is None:
            self.preview_widget = common.root.preview(self, self._preview_position)
            if self.preview_widget:
                new_label = _('Close Preview')
                if wx.Platform == '__WXGTK__':  # otherwise e.g. preview of Test_Editing2 fails sometimes
                    wx.SafeYield()
                    compat.wxWindow_SendSizeEventToParent(self.preview_widget)
        ...
```
This way this code will only be called if `self.preview_widget` is valid.

Your Thonny installation is probably using a different Python installation than if you start wxGlade otherwise.
If you go to the Thonny shell and enter
```
import sys
sys.executable
```
then you should see which one Thonny is using. You can use the same.
