### ISSUE TITLE
Combobox mistake generation

### ISSUE THREAD

**Issue by romacar** [wxGlade/wxGlade#544]
Hello,

I think the wxCombobox is incorrectly generated

**self.wxComboPersNomComplet = wx.ComboBox(self, wx.ID_ANY, choices=["ListNomComp"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)**

but it must be this according to the documentation

**_self.wxComboPersNomComplet = wx.ComboBox(self, wx.ID_ANY, choices=ListNomComp, style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)_**

Thanks and best regards
 Carlos

**Comment by reticulatus** [comment]
The wx.ComboBox constructor given in the wxPython 4.2.1 documentation is:

```
ComboBox(parent, id=ID_ANY, value="", pos=DefaultPosition,
         size=DefaultSize, choices=[], style=0, validator=DefaultValidator,
         name=ComboBoxNameStr)
```

The `choices` parameter should be a list of strings.

To add items to a combobox in wxGlade you can type each one individually as a Label in combobox's Widget tab:

![example_1](https://github.com/wxGlade/wxGlade/assets/6072789/08302995-0fcd-4f5b-906c-cf92202b2ef4)

When you generate the code, it will include a line like this:

```
self.names_combo_box = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Tom", "Dick", "Harry"], style=wx.CB_DROPDOWN)
```

Alternatively, you could define the list in another module (for example MyDefinitions.py):

```
NAMES_LIST = ["Tom", "Dick", "Harry"]
```

Then instead of entering the labels in the Widget tab, you could do something like this in the combobox's Code tab:

![example_2](https://github.com/wxGlade/wxGlade/assets/6072789/30573f7a-a923-48e2-8a8b-145c4bc7a613)

Then when you generate the code, it will include lines like this:

```
self.names_combo_box = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
self.names_combo_box.SetItems(NAMES_LIST)
```

**Comment by romacar** [comment]
Thanks for your support
